#!/bin/bash -l
# ===========================================================================
#  Batch evaluation of all trained models × all input transforms.
#
#  For each model (unet, afm), evaluates every checkpoint under:
#    none, qm_tp, qm_precip, qm_all, ot
#
#  Results land in {RESULTS_DIR}/{model}/{transform}/results.csv
# ===========================================================================

#SBATCH --account tbeucler_downscaling
#SBATCH --mail-type FAIL
#SBATCH --mail-user filippo.quarenghi@unil.ch

#SBATCH --chdir /scratch/fquareng/
#SBATCH --job-name eval
#SBATCH --output outputs/%j
#SBATCH --error  job_errors/%j

#SBATCH --partition gpu-gh
#SBATCH --gres gpu:1
#SBATCH --gres-flags enforce-binding
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 12
#SBATCH --mem 0
#SBATCH --time 24:00:00

set -euo pipefail

export SINGULARITY_BINDPATH="/work,/scratch,/users"
export SINGULARITYENV_LD_PRELOAD="/opt/hpcx/ucc/lib/libucc.so.1:/opt/hpcx/ucx/lib/libucp.so.0:/opt/hpcx/ucx/lib/libucs.so.0"

CONTAINER="/users/fquareng/singularity/dl_gh200.sif"
CODE_ROOT="/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/rainshift-uda"
OUTPUT_DIR="/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/results_rainshift_uda"
DATA_ROOT="/work/FAC/FGSE/IDYST/tbeucler/downscaling/raw_data/rainshift"

# One seed per job. Each seed reads its own trees (unet_seed<N>/,
# unet_seed<N>_oracle/) and writes its own results/seed<N>/. There is no
# --force: evaluate.py skips any run that already has metrics.json, so a
# re-run resumes instead of overwriting. The old unseeded unet/ tree and
# results/unet/ are never touched.
SEED="${SEED:?SEED must be set, e.g. SEED=42 sbatch scripts/evaluate.sh}"
UNET_DIR="${OUTPUT_DIR}/unet_seed${SEED}"
ORACLE_DIR="${OUTPUT_DIR}/unet_seed${SEED}_oracle"
AFM_DIR="${OUTPUT_DIR}/afm_seed${SEED}"
RESULTS_DIR="${OUTPUT_DIR}/results/seed${SEED}"
# Input-transform cache is seed-independent; share it across seeds.
CACHE_DIR="${OUTPUT_DIR}/results/transforms"

[[ -d "${UNET_DIR}" ]] || { echo "ERROR: ${UNET_DIR} does not exist."; exit 1; }
echo "SEED: ${SEED}   models: ${UNET_DIR}   results: ${RESULTS_DIR}"

# Point these to the 1D Wasserstein distances generated by compute_shift.py
W1_MATRIX="${CODE_ROOT}/covariate_shift_analysis/normalized/Wasserstein_1D_test.npy"
W1_META="${CODE_ROOT}/covariate_shift_analysis/normalized/Wasserstein_1D_test_variables.json"

# NOTE: "oracle" is NOT a valid --input_transform. evaluate.py defines
# _TRANSFORM_CHOICES = [none, qm_tp, qm_precip, qm_all, ot], so passing
# "oracle" made argparse abort the whole script on the second iteration.
# The oracle is a different CHECKPOINT DIRECTORY, not an input transform;
# it is evaluated separately below.
TRANSFORMS=("none") # "qm_precip" "qm_tp" "qm_all" "ot")

# AFM probabilistic settings
N_ENSEMBLE=16
SAMPLE_STEPS=20

run_python() {
    singularity exec --nv "${CONTAINER}" python "$@"
}

# -------------------------------------------------------------------
#  UNet: deterministic evaluation across all transforms
# -------------------------------------------------------------------
for tf in "${TRANSFORMS[@]}"; do
    echo "=== UNet | transform: ${tf} ==="
    run_python "${CODE_ROOT}/evaluate.py" batch \
        --exp_root "${UNET_DIR}" \
        --data_root "${DATA_ROOT}" \
        --output_dir "${RESULTS_DIR}/unet/${tf}" \
        --input_transform "${tf}" \
        --transform_cache_dir "${CACHE_DIR}" \
        --save_samples 10 \
        --eval_train
    echo ""
done

# -------------------------------------------------------------------
#  ORACLE (joint source+target training) evaluation.
#  The oracle checkpoints live in a SEPARATE output dir written by
#  `PHASE=oracle`, so they need their own --exp_root. They are ordinary
#  checkpoints: no input transform applies. Their target risk is the
#  addressable-budget denominator.
# -------------------------------------------------------------------
if [[ -d "${ORACLE_DIR}" ]]; then
    echo "=== UNet | ORACLE (joint) ==="
    run_python "${CODE_ROOT}/evaluate.py" batch \
        --exp_root "${ORACLE_DIR}" \
        --data_root "${DATA_ROOT}" \
        --output_dir "${RESULTS_DIR}/unet/oracle" \
        --input_transform none \
        --transform_cache_dir "${CACHE_DIR}" \
        --save_samples 10 \
        --eval_train
    echo ""
else
    echo "WARNING: ${ORACLE_DIR} not found; skipping oracle eval."
fi

# -------------------------------------------------------------------
#  AFM deterministic: across all transforms
# -------------------------------------------------------------------
# run_exp_afm.sh is not seeded yet (fixed afm/ tree), so this runs only once
# an afm_seed<N>/ tree exists.
if [[ -d "${AFM_DIR}" ]]; then
for tf in "${TRANSFORMS[@]}"; do
    echo "=== AFM (deterministic) | transform: ${tf} ==="
    run_python "${CODE_ROOT}/evaluate.py" batch \
        --exp_root "${AFM_DIR}" \
        --data_root "${DATA_ROOT}" \
        --output_dir "${RESULTS_DIR}/afm/${tf}" \
        --input_transform "${tf}" \
        --transform_cache_dir "${CACHE_DIR}" \
        --save_samples 10 \
        --eval_train
    echo ""
done

# # -------------------------------------------------------------------
# #  AFM probabilistic: only none + best transform (avoid 5×16-member cost)
# #  Run the full set on "none" and "ot" to compare; add others if needed.
# # -------------------------------------------------------------------
for tf in "none" "ot"; do
    echo "=== AFM (probabilistic, ${N_ENSEMBLE} members) | transform: ${tf} ==="
    run_python "${CODE_ROOT}/evaluate.py" batch \
        --exp_root "${AFM_DIR}" \
        --data_root "${DATA_ROOT}" \
        --output_dir "${RESULTS_DIR}/afm_prob/${tf}" \
        --input_transform "${tf}" \
        --transform_cache_dir "${CACHE_DIR}" \
        --n_ensemble "${N_ENSEMBLE}" \
        --sample_steps "${SAMPLE_STEPS}" \
        --save_samples 5 \
        --eval_train
    echo ""
done
else
    echo "=== AFM: ${AFM_DIR} not found; skipping AFM eval. ==="
fi

# -------------------------------------------------------------------
#  Regenerate the W1 cube with the corrected compute_shift.py (exact
#  empirical W1, shared per-domain sampling). --emit_aggregates also writes
#  the mean_inputs / max_inputs scalar matrices. The cube feeds compute_ngg,
#  which aggregates to mean_inputs internally (covariate shift, NOT the tp
#  label-shift channel).
# -------------------------------------------------------------------
#  The cube is seed-independent and overwrites files in place, so it is only
#  generated when absent. To regenerate, move the existing
#  covariate_shift_analysis/normalized/Wasserstein_1D_test* files to a
#  _trash/ folder first.
if [[ -f "${W1_MATRIX}" ]]; then
    echo "=== W1 shift cube exists (${W1_MATRIX}); not regenerating ==="
else
    echo "=== Generating W1 shift cube (normalized, test) ==="
    run_python "${CODE_ROOT}/covariate_shift_analysis/compute_shift.py" \
        --data_root "${DATA_ROOT}" \
        --domains europe_west horn-of-africa melanesia \
        --mode normalized \
        --split test \
        --emit_aggregates \
        --output_dir "${CODE_ROOT}/covariate_shift_analysis"
fi
echo ""

# -------------------------------------------------------------------
#  NGG Computation
# -------------------------------------------------------------------
echo "=== Computing NGG ==="
for model in "unet"; do # "afm"
    for tf in "${TRANSFORMS[@]}"; do
        echo "--- NGG | model: ${model} | transform: ${tf} ---"
        run_python "${CODE_ROOT}/compute_ngg_all.py" \
            --w1_matrix "${W1_MATRIX}" \
            --w1_variables "${W1_META}" \
            --results_csv "${RESULTS_DIR}/${model}/${tf}/results.csv" \
            --model "${model}" \
            --error_metric "mse_std" \
            --w1_agg "mean_inputs" \
            --output_root "${RESULTS_DIR}/ngg/${model}_${tf}"
    done
done

echo "=== Evaluation & NGG complete ==="
