#!/bin/bash -l
# ===========================================================================
#  Batch evaluation of all trained models × all input transforms.
#
#  For each model (unet, afm), evaluates every checkpoint under:
#    none, qm_tp, qm_precip, qm_all, ot
#
#  Results land in {RESULTS_DIR}/{model}/{transform}/results.csv
# ===========================================================================

#SBATCH --account tbeucler_downscaling
#SBATCH --mail-type FAIL
#SBATCH --mail-user filippo.quarenghi@unil.ch

#SBATCH --chdir /scratch/fquareng/
#SBATCH --job-name eval
#SBATCH --output outputs/%j
#SBATCH --error  job_errors/%j

#SBATCH --partition gpu-gh
#SBATCH --gres gpu:1
#SBATCH --gres-flags enforce-binding
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 12
#SBATCH --mem 0
#SBATCH --time 24:00:00

set -euo pipefail

export SINGULARITY_BINDPATH="/work,/scratch,/users"
export SINGULARITYENV_LD_PRELOAD="/opt/hpcx/ucc/lib/libucc.so.1:/opt/hpcx/ucx/lib/libucp.so.0:/opt/hpcx/ucx/lib/libucs.so.0"

CONTAINER="/users/fquareng/singularity/dl_gh200.sif"
CODE_ROOT="/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/rainshift-uda"
OUTPUT_DIR="/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/results_rainshift_uda"
RESULTS_DIR="/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/results_rainshift_uda/results"
DATA_ROOT="/work/FAC/FGSE/IDYST/tbeucler/downscaling/raw_data/rainshift"
CACHE_DIR="${RESULTS_DIR}/transforms"

# Point these to the 1D Wasserstein distances generated by compute_shift.py
W1_MATRIX="${CODE_ROOT}/covariate_shift_analysis/normalized/Wasserstein_1D_test.npy"
W1_META="${CODE_ROOT}/covariate_shift_analysis/normalized/Wasserstein_1D_test_variables.json"

TRANSFORMS=("none" "oracle") # "qm_precip") # "qm_tp" "qm_all" "ot")

# AFM probabilistic settings
N_ENSEMBLE=16
SAMPLE_STEPS=20

run_python() {
    singularity exec --nv "${CONTAINER}" python "$@"
}

# -------------------------------------------------------------------
#  UNet: deterministic evaluation across all transforms
# -------------------------------------------------------------------
for tf in "${TRANSFORMS[@]}"; do
    echo "=== UNet | transform: ${tf} ==="
    run_python "${CODE_ROOT}/evaluate.py" batch \
        --exp_root "${OUTPUT_DIR}/unet" \
        --data_root "${DATA_ROOT}" \
        --output_dir "${RESULTS_DIR}/unet/${tf}" \
        --input_transform "${tf}" \
        --transform_cache_dir "${CACHE_DIR}" \
        --save_samples 10 \
        --force
    echo ""
done

# -------------------------------------------------------------------
#  AFM deterministic: across all transforms
# -------------------------------------------------------------------
for tf in "${TRANSFORMS[@]}"; do
    echo "=== AFM (deterministic) | transform: ${tf} ==="
    run_python "${CODE_ROOT}/evaluate.py" batch \
        --exp_root "${OUTPUT_DIR}/afm" \
        --data_root "${DATA_ROOT}" \
        --output_dir "${RESULTS_DIR}/afm/${tf}" \
        --input_transform "${tf}" \
        --transform_cache_dir "${CACHE_DIR}" \
        --save_samples 10 \
        --force
    echo ""
done

# # -------------------------------------------------------------------
# #  AFM probabilistic: only none + best transform (avoid 5×16-member cost)
# #  Run the full set on "none" and "ot" to compare; add others if needed.
# # -------------------------------------------------------------------
for tf in "none" "ot"; do
    echo "=== AFM (probabilistic, ${N_ENSEMBLE} members) | transform: ${tf} ==="
    run_python "${CODE_ROOT}/evaluate.py" batch \
        --exp_root "${OUTPUT_DIR}/afm" \
        --data_root "${DATA_ROOT}" \
        --output_dir "${RESULTS_DIR}/afm_prob/${tf}" \
        --input_transform "${tf}" \
        --transform_cache_dir "${CACHE_DIR}" \
        --n_ensemble "${N_ENSEMBLE}" \
        --sample_steps "${SAMPLE_STEPS}" \
        --save_samples 5 \
        --force
    echo ""
done

# -------------------------------------------------------------------
#  Regenerate the W1 cube with the corrected compute_shift.py (exact
#  empirical W1, shared per-domain sampling). --emit_aggregates also writes
#  the mean_inputs / max_inputs scalar matrices. The cube feeds compute_ngg,
#  which aggregates to mean_inputs internally (covariate shift, NOT the tp
#  label-shift channel).
# -------------------------------------------------------------------
echo "=== Regenerating W1 shift cube (normalized, test) ==="
run_python "${CODE_ROOT}/compute_shift.py" \
    --data_root "${DATA_ROOT}" \
    --domains europe_west horn-of-africa melanesia \
    --mode normalized \
    --split test \
    --emit_aggregates \
    --output_dir "${CODE_ROOT}/covariate_shift_analysis"
echo ""

# -------------------------------------------------------------------
#  NGG Computation
# -------------------------------------------------------------------
echo "=== Computing NGG ==="
for model in "unet"; do # "afm"
    for tf in "${TRANSFORMS[@]}"; do
        echo "--- NGG | model: ${model} | transform: ${tf} ---"
        run_python "${CODE_ROOT}/compute_ngg_all.py" \
            --w1_matrix "${W1_MATRIX}" \
            --w1_variables "${W1_META}" \
            --results_csv "${RESULTS_DIR}/${model}/${tf}/results.csv" \
            --model "${model}" \
            --error_metric "mse_std" \
            --w1_agg "mean_inputs" \
            --output_root "${RESULTS_DIR}/ngg/${model}_${tf}"
    done
done

echo "=== Evaluation & NGG complete ==="